### ISSUE TITLE
configure with non default install dirs

### ISSUE THREAD

**Issue by mingodad** [msharov/utio#1]
Hello !
I have ustl and other libraries installed under $HOME/local and there is no way to specify alternative paths to search for libraries. I exported CXXFLAGS and LDFLAGS and they go to the final Config.mk but for config.h nothing for HAVE_USTL_H .

Also the stderr redirection here has the same problem that ustl had before "&>"  -> " 2>&1"

Cheers !

**Comment by msharov** [comment]
Fixed by 7fa42c0ae958ab9b93a4450d9c64be67a90ac951 and 4cde167291cafb16c262f0b39d85fc8fae7164ba. The custom directories are specified by --customincdir and --customlibdir options to configure. If you have uSTL installed in $HOME/local then simply specifying --prefix=$HOME/local to utio configure will work. That is the way I have it installed on my system.

On an unrelated note, the correct user prefix compliant with the XDG spec is $HOME/.local, with the dot.
